# Generated by Django 3.1.2 on 2020-10-30 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('features', models.TextField(max_length=1500, verbose_name='Features')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('position', models.CharField(choices=[('MANAGER', 'Manager'), ('PRESIDETN', 'President'), ('VICE PRESIDENT', 'Vice president'), ('MANAGER', 'Manager'), ('TRAINEE', 'Trainee')], default='Trainee', max_length=50, verbose_name='Position')),
                ('photo', models.ImageField(default='unknown.png', upload_to='employees_photo/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('street', models.CharField(max_length=40, verbose_name='Street')),
                ('address', models.CharField(max_length=60, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Age')),
                ('description', models.TextField(max_length=1500, verbose_name='Description')),
                ('receipt_date', models.DateField(verbose_name='Receipt date')),
                ('animal_kind', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('CAT', 'Cat'), ('DOG', 'Dog'), ('HAMSTER', 'Hamster'), ('RABBIT', 'Rabbit'), ('PARROT', 'Parrot')], default='UNKNOWN', max_length=10, verbose_name='Animal kind')),
                ('photo', models.ImageField(default='unknown.png', upload_to='animals_photo/', verbose_name='Photo')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_breed', to='shelter.breed', verbose_name='Breed')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_owner', to='shelter.owner', verbose_name='Owner')),
            ],
        ),
    ]
