# Generated by Django 3.1.2 on 2020-10-22 11:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('breed', models.CharField(max_length=30, verbose_name='Breed')),
                ('description', models.TextField(verbose_name='Description')),
                ('receipt_date', models.DateField(verbose_name='Receipt date')),
                ('animal_kind', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('CAT', 'Cat'), ('DOG', 'Dog'), ('HAMSTER', 'Hamster'), ('RABBIT', 'Rabbit')], default='UNKNOWN', max_length=10, verbose_name='Animal kind')),
                ('photo', models.ImageField(default='unknown.png', upload_to='animals_photo/%Y/%m/%d', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='First name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('address', models.CharField(max_length=30, verbose_name='Address')),
            ],
        ),
    ]
