# Generated by Django 3.1.2 on 2020-10-23 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('features', models.TextField(max_length=150, verbose_name='Features')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('street', models.CharField(max_length=40, verbose_name='Street')),
                ('address', models.CharField(max_length=60, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Age')),
                ('description', models.TextField(verbose_name='Description')),
                ('receipt_date', models.DateField(verbose_name='Receipt date')),
                ('animal_kind', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('CAT', 'Cat'), ('DOG', 'Dog'), ('HAMSTER', 'Hamster'), ('RABBIT', 'Rabbit'), ('PARROT', 'Parrot')], default='UNKNOWN', max_length=10, verbose_name='Animal kind')),
                ('photo', models.ImageField(default='unknown.png', upload_to='animals_photo/', verbose_name='Photo')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_breed', to='shelter.breed', verbose_name='Breed')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_owner', to='shelter.owner', verbose_name='Owner')),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
    ]
