# Generated by Django 3.1.2 on 2020-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_auto_20201023_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='unknown.png', upload_to='animals_photo/', verbose_name='Photo'),
        ),
    ]
