# Generated by Django 3.1.2 on 2020-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Trainee', max_length=50, verbose_name='Position'),
        ),
    ]
