# Generated by Django 3.1.2 on 2020-10-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('PRESIDETN', 'President'), ('VICE PRESIDENT', 'Vice president'), ('MANAGER', 'Manager'), ('TRAINEE', 'Trainee')], default='Trainee', max_length=50, verbose_name='Position'),
        ),
    ]
