# Generated by Django 3.1.2 on 2020-10-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_auto_20201024_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='features',
            field=models.TextField(max_length=1500, verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Description'),
        ),
    ]
