# Generated by Django 3.1.2 on 2020-10-29 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_auto_20201028_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.AddField(
            model_name='breed',
            name='my_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='my_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='my_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='my_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
