# Generated by Django 3.1.2 on 2020-10-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0008_auto_20201029_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='my_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='my_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='my_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='my_id',
            new_name='id',
        ),
    ]
