# Generated by Django 3.1.2 on 2020-10-29 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('author_name', models.CharField(max_length=50, verbose_name='Author name')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('message_data', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
